version: '3'

services:
  server:
    build: ./server
    networks:
      - sensorNet
  client:
    build: ./newSensor/sensor
    environment:
      - SENSOR_NAME=sensor1
      - SENSOR_VALUE=10
    networks:
      - sensorNet
  supersensor:
    build: ./_sensor
    environment:
      - SENSOR_NAME=sensor2
      - SENSOR_VALUE=30
    networks:
      - sensorNet

networks:
  sensorNet:
