version: '3'

services:
  server:
    build: ./server
    networks:
      - sensorNet
  mavensensor:
    build: ./sensor/mvn-sensor
    environment:
      - SENSOR_TYPE=SHOP
      - SENSOR_VALUE=10
    networks:
      - sensorNet
  gosensor:
    build: ./sensor/go-sensor
    environment:
      - SENSOR_NAME=sensor2
      - SENSOR_VALUE=30
    networks:
      - sensorNet

networks:
  sensorNet:
